### ISSUE TITLE
Error en la intrucción dd

### ISSUE THREAD

**Issue by RafaelAybar** [RafaelAybar/Charla-bash-nivel-medio#2]
Todo el script va bien pero me falla la instrucción `dd`

https://github.com/RafaelAybar/Charla-bash-nivel-medio/blob/master/instalacionisos.sh

**Comment by JuanjoSalvador** [comment]
Explica mejor el problema, y lo mismo te puedo echar una mano: ¿devuelve algún error concreto? Se más específico, plis.

**Comment by jorgesumle** [comment]
dd if=$rutapen of=$ruta bs=4094 conv=noerror

<del>Primero, ¿por qué 4094? 
Los tamaños de los bloques en cualquier ordenador suelen ser múltiplos de 2. Como tú lo quieres hacer es creo con 2<sup>12</sup> (4084).</del> 

> bs=size 
> 
> ```
> sets both input and output block sizes to size bytes. You can suffix this decimal number with w, b, k, or xnumber to multiply it by 2, 512, 1024, or number respectively. 
> ```

EDITO: Aquí me he equivocado. 512 \* 8 = 4096. 

> 512 bytes (the traditional block size of disks, and POSIX-mandated size of "a block").

Está bien como estaba. Gracias, @RafaelAybar, en el [enlace](https://en.wikipedia.org/wiki/Dd_%28Unix%29) que has pasado viene bien aclarado. Perdón por la confusión.

¿Lo de conv=noerror qué hace? No entiendo muy bien lo que dice en la página de manual de `dd`. Parece que ignora los érrores. ¿Por qué lo has puesto?

>  conv=CONVS
>               convert the file as per the comma separated symbol list
> 
> ```
>    noerror
>           continue after read errors
> ```

¿Cómo lo estás probando? Si los estás probando en un USB (/dev/sdb o similares) te va a pedir el permiso del superusuario sudo y te saltará un error diciendo que no tienes permisos para ejecutar esa instrucción.

> echo "Ahora introduce la ruta donde está el pendrive"
>                 read rutapen
>                 if [[ ( -n "$rutapen" ) && ( -d "$rutapen" ) ]]
>                 then
>                         # Aquí ejecutamos la instrucción que permite grabar las isos booteables
>                         dd if=$rutapen of=$ruta bs=4094 conv=noerror
>                 else
>                         echo "La ruta no es correcta"
>                 fi

Otra cosa. Compruebas si la ruta del pendrive es un directorio. No has llegado siquiera a ejecutar la instrucción `dd`, según el código actual, porque la condición nunca se cumple. Lo de `-n "$rutapen"`sobra. Un pendrive es un dispositivo de bloque. Fijate en primera letra de la salida de la instrucción ls -l, la b quiere decir que es un dispositivo de bloque.

$ ls -l /dev/sdb
**b**rw-rw---- 1 root disk 8, 16 oct  6 15:42 sdb

**Comment by jorgesumle** [comment]
También falla la condición `elif [ -f $ruta ]`, por lo mismo de antes. La ruta corresponde a un dispositivo de bloque (-b), no a un fichero (-f).

**Comment by RafaelAybar** [comment]
No sabía que un pendrive era un dispositivo de bloque, la documentación de la sintaxis la saqué de de la wikipedia:https://en.wikipedia.org/wiki/Dd_%28Unix%29

**Comment by RafaelAybar** [comment]
```
La ruta no es correcta                                                                                                                                                                                                                                                         
Bienvenido al instalador de sistemas operativos en pendrive                                                                                                                                                                                                                    
Indica dónde está la iso a intalar                                                                                                                                                                                                                                             
Si quires salir pulsa la tecla p                                                                                                                                                                                                                                               
/media/rafa/Elements/kdeneon.iso                                                                                                                                                                                                                                               
Ahora introduce la ruta donde está el pendrive                                                                                                                                                                                                                                 
"/media/rafa/LINUX MINT"                                                                                                                                                                                                                                                       
La ruta no es correcta                
```

Con he puesto el parámetro -d

**Comment by RafaelAybar** [comment]
@JuanjoSalvador , @jorgesumle  He probado esto:

```
#!/bin/bash
while true
do
echo "Bienvenido al instalador de sistemas operativos en pendrive"
echo "Indica dónde está la iso a intalar"
echo "Si quires salir pulsa la tecla p "
read ruta
        if [ $ruta = "p"  ]
                then
                        exit
        elif [ -z $ruta ]
                then
                         echo "Oiga, introduzca la ruta"
                 elif [ -f $ruta ]
                         #Aquí comprobamos que la variable ruta no esté vacía y sea la ruta exacta donde cargar la imagen del sistema operativo a instalar.
                         then
                                echo "Ahora introduce la ruta donde está el pendrive"
                                        read rutapen
                                                 if [  -d "$rutapen" ]
                                                        then
                                                                dd if="$rutapen" of="$ruta"
                                                                #Aquí ejecutamos la instrucción que permite grabar las isos booteables
                                                        else
                                                                echo "La ruta no es correcta"
                                                fi
        fi

done



```

Pero me da este error:

```
Bienvenido al instalador de sistemas operativos en pendrive
Indica dónde está la iso a intalar
Si quires salir pulsa la tecla p 
/media/rafa/Elements/kdeneon.iso
Ahora introduce la ruta donde está el pendrive
/media/rafa/LINUX MINT
dd: error al leer '/media/rafa/LINUX MINT': Es un directorio
0+0 registros leídos
0+0 registros escritos
0 bytes copied, 0,000173048 s, 0,0 kB/s
Bienvenido al instalador de sistemas operativos en pendrive
Indica dónde está la iso a intalar
Si quires salir pulsa la tecla p 
´´´
```

**Comment by jorgesumle** [comment]
Esa ruta no es correcta: `/media/rafa/LINUX MINT`. Esa ruta la crea GNU/Linux cuando el pendrive está montado para acceder a los archivos. El dispositivo (es decir, el USB en sí) es /dev/sd**x** (la x puede ser b, c, d...). Para listar todos los dispositivos de bloque puedes utilizar la instrucción `lsblk`, uno de ellos es el USB. Cuidado extremo cuando hagas pruebas. **No uses `dd` para escribir en el disco duro (/dev/sda)**

**Comment by RafaelAybar** [comment]
@jorgesumle No sirve con -b /deb/sdax, me dice que la ruta no es válida.

**Comment by jorgesumle** [comment]
> @jorgesumle No sirve con -b /deb/sdax, me dice que la ruta no es válida.

La has escrito mal: has puesto una b en vez de una v en; la carpeta se llama `/dev` y `sdax` no creo que exista. La ruta para USBs es `/dev/sdb` generalmente.
